---

- name: All machines get OpenSCAP scanner installed
  hosts: all
  sudo: true
  roles:
    - openscap
    - harden
    - dashboard-auth-key

- name: Install SCAP Security Content (SSG) and GovReady on Dashboard
  hosts: dashboard
  roles:
    - scap-security-guide
    - govready
    - publish-key