---

- name: All machines get OpenSCAP scanner installed
  hosts: all
  sudo: true
  roles:
    - openscap
    - harden

# - name: Install apache/php/mysql/composer/drush
#   hosts: server
#   vars_files:
#     - vars/drupal.yml
#   roles:
#     - geerlingguy.drupal
#     - drupal-security
#   sudo: true

- name: Install SCAP Security Content (SSG) and GovReady on 'dashboard'
  hosts: dashboard
  roles:
    - scap-security-guide
    - govready
#   - govready-scan (This is not yet working)
